### PR TITLE
Update commands

### PR DESCRIPTION
**Pull request by Victim-NH**
Insert AddMonster in commandpacketcontroller.cs

### CODE REVIEW

**Comment by Fizo55** [comment]
Where is the AddMonsterPacket ?

**Comment by Victim-NH** [comment]
Entered now!

**Comment by Fizo55** [comment]
"LogHelper.Instance.InsertCommandLog(Session.Character.CharacterId, addMonsterPacket, Session.IpAddress);" NosCore has not log for the commands ..

**Comment by Fizo55** [comment]
GetNpc does not still exist on NosCore "ServerManager.Instance.GetNpc"

**Comment by Fizo55** [comment]
To say that NosCore != OpenNos

**Comment by Victim-NH** [comment]
Remove log and change GetNPC :)

**Comment by 0Lucifer0** [comment]
The goal is not to copy past things into noscore without understanding it.

**Pull request closed without merging**
